### PR TITLE
Use Custom Ship Log Modes utility mod

### PR DESCRIPTION
**Pull request by dgarroDC**
Use the new [Custom Ship Log Modes](https://github.com/dgarroDC/CustomShipLogModes) utility mod for better compatibility and functionality with other mods adding modes. 

PR includes version bumping.

The mod isn't in the database yet (https://github.com/ow-mods/ow-mod-db/pull/445) so don't merge this PR yet!

### CODE REVIEW

**Comment by Hawkbat** [comment]
Nice! I was planning on adding your mod as a dependency anyway, so this is fantastic. Thanks for the PR! I'll wait until your mod is published to merge it.

**Comment by dgarroDC** [comment]
The mod was published some days ago @Hawkbat, it didn't trigger the discord `@New Mod Notifications` because the release was already 24 hours old when merged

**Comment by Hawkbat** [comment]
I'll test this out locally when I get off work today and if everything
looks good I'll merge and release 👍

**Comment by Hawkbat** [comment]
Sorry for not getting to this last month. Merging it now

**Pull request merged**
